version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pipx install poetry
      - poetry export --only read-the-docs -o requirements.txt
      - poetry install
      - poetry run python -m tools.build_theme_color_doc

python:
  install:
    - path: .
    - requirements: requirements.txt
