name: codeql

on: [push, pull_request]

jobs:
  pre-commit:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Bootstrap poetry
      run: curl -sL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -

    - name: Update PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure poetry
      run: poetry config virtualenvs.in-project true

    - name: Install dependencies
      run: poetry install

    - uses: pre-commit/action@v2.0.3
