on:
  push:
    paths-ignore:
      - "*.md"
      - "*.gitignore"
      - "*.pre-commit-config.yaml"
      - "LICENSE.txt"
  pull_request:
    paths-ignore:
      - "*.md"
      - "*.gitignore"
      - "*.pre-commit-config.yaml"
      - "LICENSE.txt"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        qt-lib: [pyqt, pyside]
        include:
          - python-version: "3.7"
            qt-lib: "pyqt"
            qt-version: "PyQt5~=5.12.0"
          - python-version: "3.7"
            qt-lib: "pyside"
            qt-version: "PySide2~=5.12.0"
          - python-version: "3.8"
            qt-lib: "pyqt"
            qt-version: "PyQt5~=5.15.0"
          - python-version: "3.8"
            qt-lib: "pyside"
            qt-version: "PySide6"
          - python-version: "3.9"
            qt-lib: "pyqt"
            qt-version: "PyQt6"
          - python-version: "3.9"
            qt-lib: "pyside"
            qt-version: "PySide6"
          - python-version: "3.10"
            qt-lib: "pyqt"
            qt-version: "PyQt6"
          - python-version: "3.10"
            qt-lib: "pyside"
            qt-version: "PySide6"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: python -m pip install ${{ matrix.qt-version }} pytest

    - name: 'Debug Info'
      run: |
        echo python location: `which python`
        echo python version: `python --version`
        echo pytest location: `which pytest`
        echo installed packages
        python -m pip list
      shell: bash

    - name: Run pytest
      run: python -m pytest tests -v
